"""add risk tables equity snapshots api call log ticker profile

Revision ID: 00f5798d2664
Revises: b27de9aa16ec
Create Date: 2026-04-20 22:09:27.041513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f5798d2664'
down_revision: Union[str, Sequence[str], None] = 'b27de9aa16ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_kind', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_call_log_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_call_log_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_call_log_ts'), ['ts'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('high_water_mark', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_snapshots_ts'), ['ts'], unique=False)

    op.create_table('ticker_profile',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('ticker_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticker_profile_sector'), ['sector'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticker_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticker_profile_sector'))

    op.drop_table('ticker_profile')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_ts'))

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('api_call_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_call_log_ts'))
        batch_op.drop_index(batch_op.f('ix_api_call_log_status'))
        batch_op.drop_index(batch_op.f('ix_api_call_log_provider'))

    op.drop_table('api_call_log')
    # ### end Alembic commands ###
