"""initial schema with dedup_key

Revision ID: c6c1dea749a6
Revises: 
Create Date: 2026-04-19 19:34:03.061613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c1dea749a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclosed_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('person_name', sa.String(length=256), nullable=False),
    sa.Column('person_role', sa.String(length=256), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('amount_low', sa.Float(), nullable=True),
    sa.Column('amount_high', sa.Float(), nullable=True),
    sa.Column('amount_exact', sa.Float(), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disclosed_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disclosed_trades_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_disclosed_trades_filing_date'), ['filing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosed_trades_person_name'), ['person_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosed_trades_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosed_trades_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosed_trades_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('person_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('canonical', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_aliases_alias'), ['alias'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_aliases_canonical'), ['canonical'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_kind'), ['kind'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acted_on', sa.Boolean(), nullable=False),
    sa.Column('acted_order_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_strategy_name'), ['strategy_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ticker'), ['ticker'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('alpaca_order_id', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rationale_note_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_alpaca_order_id'), ['alpaca_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_client_order_id'), ['client_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_strategy_name'), ['strategy_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_ticker'), ['ticker'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('entry_signal_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hard_stop', sa.Float(), nullable=True),
    sa.Column('trail_peak', sa.Float(), nullable=True),
    sa.Column('trail_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['entry_signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_strategy_name'), ['strategy_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_ticker'), ['ticker'], unique=True)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('alpaca_fill_id', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_alpaca_fill_id'), ['alpaca_fill_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fills_filled_at'), ['filled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))
        batch_op.drop_index(batch_op.f('ix_fills_filled_at'))
        batch_op.drop_index(batch_op.f('ix_fills_alpaca_fill_id'))

    op.drop_table('fills')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_ticker'))
        batch_op.drop_index(batch_op.f('ix_positions_strategy_name'))

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_ticker'))
        batch_op.drop_index(batch_op.f('ix_orders_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_orders_client_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_alpaca_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ticker'))
        batch_op.drop_index(batch_op.f('ix_signals_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_signals_generated_at'))

    op.drop_table('signals')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_kind'))
        batch_op.drop_index(batch_op.f('ix_risk_events_created_at'))

    op.drop_table('risk_events')
    with op.batch_alter_table('person_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_aliases_canonical'))
        batch_op.drop_index(batch_op.f('ix_person_aliases_alias'))

    op.drop_table('person_aliases')
    with op.batch_alter_table('disclosed_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disclosed_trades_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_disclosed_trades_ticker'))
        batch_op.drop_index(batch_op.f('ix_disclosed_trades_source'))
        batch_op.drop_index(batch_op.f('ix_disclosed_trades_person_name'))
        batch_op.drop_index(batch_op.f('ix_disclosed_trades_filing_date'))
        batch_op.drop_index(batch_op.f('ix_disclosed_trades_dedup_key'))

    op.drop_table('disclosed_trades')
    # ### end Alembic commands ###
