/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Info */
        get: operations["account_info_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Limits */
        get: operations["account_limits_account_limits_get"];
        /** Update Account Limits */
        put: operations["update_account_limits_account_limits_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Account */
        post: operations["pause_account_account_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Account */
        post: operations["resume_account_account_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance */
        get: operations["performance_portfolio_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Performance Review
         * @description S3.5 honest review: return is never served without benchmark + drawdown beside it.
         */
        get: operations["performance_review_portfolio_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote */
        get: operations["quote_quotes__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Agent Run */
        post: operations["trigger_agent_run_agent_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suggestions */
        get: operations["list_suggestions_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{suggestion_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_suggestions__suggestion_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{suggestion_id}/modify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modify */
        post: operations["modify_suggestions__suggestion_id__modify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{suggestion_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss */
        post: operations["dismiss_suggestions__suggestion_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{suggestion_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace */
        get: operations["trace_suggestions__suggestion_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Onboarding Status */
        get: operations["onboarding_status_onboarding_get"];
        put?: never;
        /** Complete Onboarding */
        post: operations["complete_onboarding_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Digest */
        post: operations["run_digest_digest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Journal */
        get: operations["read_journal_journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft */
        post: operations["draft_strategies_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest */
        post: operations["backtest_strategies__strategy_id__backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate */
        post: operations["activate_strategies__strategy_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive */
        post: operations["archive_strategies__strategy_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatif/shock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shock */
        post: operations["shock_whatif_shock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatif/trade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade Preview */
        post: operations["trade_preview_whatif_trade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountOut */
        AccountOut: {
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Base Currency */
            base_currency: string;
            /** Starting Equity */
            starting_equity: string;
            /** Paused */
            paused: boolean;
            /** Trading Mode */
            trading_mode: string;
        };
        /** AgentRunOut */
        AgentRunOut: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Suggestions */
            suggestions: {
                [key: string]: unknown;
            }[];
        };
        /** BacktestOut */
        BacktestOut: {
            /** Strategy Id */
            strategy_id: string;
            /** Windows */
            windows: components["schemas"]["BacktestWindowOut"][];
            /** Total Return Pct */
            total_return_pct: number;
            /** Buy Hold Return Pct */
            buy_hold_return_pct: number;
            /** Benchmark Return Pct */
            benchmark_return_pct: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Closed Trades */
            closed_trades: number;
            /** Win Rate Pct */
            win_rate_pct: number | null;
            /** Windows Beating Buy Hold */
            windows_beating_buy_hold: number;
            /** Small Sample */
            small_sample: boolean;
            /** Days */
            days: number;
            /** Caveats */
            caveats: string[];
        };
        /** BacktestWindowOut */
        BacktestWindowOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Strategy Return Pct */
            strategy_return_pct: number;
            /** Buy Hold Return Pct */
            buy_hold_return_pct: number;
            /** Trades */
            trades: number;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** History */
            history?: components["schemas"]["ChatMessage"][];
        };
        /** ClosedTradesOut */
        ClosedTradesOut: {
            /** Closed Trades */
            closed_trades: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate Pct */
            win_rate_pct: number | null;
            /** Small Sample */
            small_sample: boolean;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Reason */
            reason?: string | null;
            /** Qty */
            qty?: string | null;
        };
        /** DecisionResult */
        DecisionResult: {
            /** Suggestion */
            suggestion: {
                [key: string]: unknown;
            };
            order?: components["schemas"]["OrderOut"] | null;
            /**
             * Violations
             * @default []
             */
            violations: components["schemas"]["ViolationOut"][];
        };
        /** DigestOut */
        DigestOut: {
            notification: components["schemas"]["NotificationOut"];
            /** Created */
            created: boolean;
        };
        /** FillOut */
        FillOut: {
            /** Qty */
            qty: string;
            /** Price */
            price: string;
            /** Fee */
            fee: string;
            /** Filled At */
            filled_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Shape returned by ``GET /health`` (frozen contract for S0.1).
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Trading Mode */
            trading_mode: string;
        };
        /** JournalEntryOut */
        JournalEntryOut: {
            /** Id */
            id: string;
            /** Entry Type */
            entry_type: string;
            /** Ref Id */
            ref_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** JournalOut */
        JournalOut: {
            /** Entries */
            entries: components["schemas"]["JournalEntryOut"][];
            /** Nudges */
            nudges: components["schemas"]["NudgeOut"][];
        };
        /** LimitsOut */
        LimitsOut: {
            /** Max Position Pct */
            max_position_pct: string | null;
            /** Max Asset Class Pct */
            max_asset_class_pct: {
                [key: string]: string;
            };
            /** Max Trades Per Week */
            max_trades_per_week: number | null;
            /** Cash Floor Pct */
            cash_floor_pct: string | null;
            /** Per Suggestion Max Pct */
            per_suggestion_max_pct: string | null;
            /** Drawdown Pause Pct */
            drawdown_pause_pct: string | null;
        };
        /** LimitsUpdateOut */
        LimitsUpdateOut: {
            limits: components["schemas"]["LimitsOut"];
            /** Profile */
            profile: string;
            /** Loosened */
            loosened: string[];
        };
        /** LimitsUpdateRequest */
        LimitsUpdateRequest: {
            /** Max Position Pct */
            max_position_pct: string;
            /** Max Asset Class Pct */
            max_asset_class_pct: {
                [key: string]: string;
            };
            /** Max Trades Per Week */
            max_trades_per_week: number;
            /** Cash Floor Pct */
            cash_floor_pct: string;
            /** Per Suggestion Max Pct */
            per_suggestion_max_pct: string;
            /** Drawdown Pause Pct */
            drawdown_pause_pct: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Onboarded
             * @default false
             */
            onboarded: boolean;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Read At */
            read_at: string | null;
        };
        /** NudgeOut */
        NudgeOut: {
            /** Kind */
            kind: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
        };
        /** OnboardingOut */
        OnboardingOut: {
            /** Profile */
            profile: string;
            limits: components["schemas"]["LimitsOut"];
            /** Onboarded */
            onboarded: boolean;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /** Experience */
            experience: string;
            /** Drop Reaction */
            drop_reaction: string;
            /** Goal */
            goal: string;
        };
        /** OnboardingStatusOut */
        OnboardingStatusOut: {
            /** Onboarded */
            onboarded: boolean;
            /** Profiles */
            profiles: {
                [key: string]: components["schemas"]["LimitsOut"];
            };
        };
        /** OrderOut */
        OrderOut: {
            /** Id */
            id: string;
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Side */
            side: string;
            /** Order Type */
            order_type: string;
            /** Qty */
            qty: string;
            /** Limit Price */
            limit_price: string | null;
            /** Status */
            status: string;
            /** Rejected Reason */
            rejected_reason: string | null;
            /** Created At */
            created_at: string;
            fill?: components["schemas"]["FillOut"] | null;
        };
        /** OrderRequest */
        OrderRequest: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Side */
            side: string;
            /** Order Type */
            order_type: string;
            /** Qty */
            qty: string;
            /** Limit Price */
            limit_price?: string | null;
        };
        /** OrderResult */
        OrderResult: {
            order: components["schemas"]["OrderOut"];
            /** Violations */
            violations: components["schemas"]["ViolationOut"][];
            /** Replayed */
            replayed: boolean;
        };
        /** PerformanceOut */
        PerformanceOut: {
            /** Points */
            points: components["schemas"]["PerformancePointOut"][];
            /** Return Pct */
            return_pct: number;
            /** Benchmark Return Pct */
            benchmark_return_pct: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Current Drawdown Pct */
            current_drawdown_pct: number;
            /** Benchmark Symbol */
            benchmark_symbol: string;
        };
        /** PerformancePointOut */
        PerformancePointOut: {
            /** Day */
            day: string;
            /** Equity */
            equity: string;
            /** Benchmark Equity */
            benchmark_equity: string;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Equity */
            equity: string;
            /** Cash */
            cash: string;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Allocation Pct */
            allocation_pct: {
                [key: string]: number;
            };
        };
        /** PositionImpactOut */
        PositionImpactOut: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Value Before */
            value_before: string;
            /** Value After */
            value_after: string;
            /** Applied Pct */
            applied_pct: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Quantity */
            quantity: string;
            /** Avg Cost */
            avg_cost: string;
            /** Market Value */
            market_value: string;
            /** Unrealized Pl */
            unrealized_pl: string;
            /** Allocation Pct */
            allocation_pct: number;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Symbol */
            symbol: string;
            /** Price */
            price: string;
            /** As Of */
            as_of: string;
            /** Source */
            source: string;
            /** Is Stale */
            is_stale: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** ReviewOut */
        ReviewOut: {
            performance: components["schemas"]["PerformanceOut"];
            trades: components["schemas"]["ClosedTradesOut"];
            /** Verdict */
            verdict: string;
            /** Disclaimers */
            disclaimers: string[];
        };
        /** ShockImpactOut */
        ShockImpactOut: {
            /** Equity Before */
            equity_before: string;
            /** Equity After */
            equity_after: string;
            /** Equity Change Pct */
            equity_change_pct: string;
            /** Cash */
            cash: string;
            /** Positions */
            positions: components["schemas"]["PositionImpactOut"][];
            /** Allocation After Pct */
            allocation_after_pct: {
                [key: string]: number;
            };
            /** Would Trip Drawdown Pause */
            would_trip_drawdown_pause: boolean;
            /** Drawdown Pause Pct */
            drawdown_pause_pct: string | null;
        };
        /** ShockRequest */
        ShockRequest: {
            /**
             * Equity Pct
             * @default 0
             */
            equity_pct: string;
            /**
             * Crypto Pct
             * @default 0
             */
            crypto_pct: string;
            /** Symbol Overrides */
            symbol_overrides?: {
                [key: string]: string;
            };
        };
        /** StrategyDraftRequest */
        StrategyDraftRequest: {
            /** Text */
            text: string;
        };
        /** StrategyOut */
        StrategyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Text */
            source_text: string;
            /** Status */
            status: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Description */
            description: string;
            /** Created At */
            created_at: string;
            /** Last Backtest */
            last_backtest?: {
                [key: string]: unknown;
            } | null;
        };
        /** SuggestionListOut */
        SuggestionListOut: {
            /** Suggestions */
            suggestions: {
                [key: string]: unknown;
            }[];
        };
        /**
         * TraceOut
         * @description S2.6 — the full 'show your work' trail: candidate logic → source data → model metadata.
         */
        TraceOut: {
            /** Suggestion Id */
            suggestion_id: string;
            /** Candidate Ref */
            candidate_ref: string;
            /** Signal Features */
            signal_features: {
                [key: string]: unknown;
            }[];
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            }[];
            /** Sizing */
            sizing: {
                [key: string]: unknown;
            };
            /** Prompt Version */
            prompt_version: string;
            /** Model Version */
            model_version: string;
            /** Agent Run Id */
            agent_run_id: string | null;
            /** Snapshot Id */
            snapshot_id: string | null;
            /** Snapshot As Of */
            snapshot_as_of: string | null;
            /** Risk Events */
            risk_events: {
                [key: string]: unknown;
            }[];
        };
        /** TradePreviewOut */
        TradePreviewOut: {
            /** Allowed */
            allowed: boolean;
            /** Violations */
            violations: components["schemas"]["ViolationOut"][];
            /** Est Price */
            est_price: string;
            /** Cash After */
            cash_after: string;
            /** Position Value After */
            position_value_after: string;
            /** Position Allocation After Pct */
            position_allocation_after_pct: number;
            /** Cash Allocation After Pct */
            cash_allocation_after_pct: number;
        };
        /** TradePreviewRequest */
        TradePreviewRequest: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Side */
            side: string;
            /** Qty */
            qty: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViolationOut */
        ViolationOut: {
            /** Limit Type */
            limit_type: string | null;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_info_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_limits_account_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_limits_account_limits_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LimitsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsUpdateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_account_account_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_account_account_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_portfolio_performance_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_review_portfolio_review_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_quotes__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_orders_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_agent_run_agent_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suggestions_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_suggestions__suggestion_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modify_suggestions__suggestion_id__modify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_suggestions__suggestion_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_suggestions__suggestion_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboarding_status_onboarding_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_onboarding_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_digest_digest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_journal_journal_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_strategies_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_strategies__strategy_id__backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_strategies__strategy_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_strategies__strategy_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shock_whatif_shock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShockImpactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trade_preview_whatif_trade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                alphadash_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
