"""S0.2 initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-08 23:35:39.396863

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column(
            "mode", sa.Enum("paper", "real", name="account_mode", native_enum=False), nullable=False
        ),
        sa.Column("base_currency", sa.String(length=8), nullable=False),
        sa.Column("starting_equity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_accounts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_table(
        "risk_profiles",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "conservative",
                "balanced",
                "curious",
                "custom",
                name="risk_profile_name",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("max_position_pct", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("max_asset_class_pct", sa.JSON(), nullable=False),
        sa.Column("max_trades_per_week", sa.Integer(), nullable=False),
        sa.Column("cash_floor_pct", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("per_suggestion_max_pct", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("drawdown_pause_pct", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_risk_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_profiles")),
    )
    op.create_table(
        "watchlists",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_watchlists_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum("scheduled", "event", "on_demand", name="agent_run_trigger", native_enum=False),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "completed", "failed", name="agent_run_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("cost_tokens", sa.Integer(), nullable=True),
        sa.Column("input_snapshot_id", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_agent_runs_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["input_snapshot_id"],
            ["data_snapshots.id"],
            name=op.f("fk_agent_runs_input_snapshot_id_data_snapshots"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_table(
        "cash_balances",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_cash_balances_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_balances")),
        sa.UniqueConstraint("account_id", "currency", name=op.f("uq_cash_balances_account_id")),
    )
    op.create_table(
        "journal_entries",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "suggestion",
                "decision",
                "order",
                "fill",
                "risk_event",
                "note",
                name="journal_entry_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ref_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_journal_entries_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
    )
    op.create_table(
        "positions",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "asset_class",
            sa.Enum("equity", "crypto", name="asset_class", native_enum=False),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("avg_cost", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_positions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("account_id", "symbol", name=op.f("uq_positions_account_id")),
    )
    op.create_table(
        "risk_limits",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column(
            "limit_type",
            sa.Enum(
                "max_position_pct",
                "max_asset_class_pct",
                "max_trades_per_week",
                "cash_floor_pct",
                "per_suggestion_max_pct",
                "drawdown_pause_pct",
                name="risk_limit_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_risk_limits_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_limits")),
    )
    op.create_table(
        "suggestions",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("confidence_basis", sa.Text(), nullable=False),
        sa.Column("candidate_ref", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "approved",
                "modified",
                "dismissed",
                "expired",
                "blocked",
                name="suggestion_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("falsifier", sa.Text(), nullable=False),
        sa.Column("reversibility", sa.Text(), nullable=False),
        sa.Column("sizing", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("worst_case", sa.Text(), nullable=False),
        sa.Column("blocked_reason", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_suggestions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggestions")),
    )
    op.create_table(
        "watchlist_items",
        sa.Column("watchlist_id", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "asset_class",
            sa.Enum("equity", "crypto", name="asset_class", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
            name=op.f("fk_watchlist_items_watchlist_id_watchlists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint("watchlist_id", "symbol", name=op.f("uq_watchlist_items_watchlist_id")),
    )
    op.create_table(
        "data_snapshots",
        sa.Column("agent_run_id", sa.String(length=32), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_data_snapshots_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_snapshots")),
    )
    op.create_table(
        "decisions",
        sa.Column("suggestion_id", sa.String(length=32), nullable=False),
        sa.Column(
            "action",
            sa.Enum("approve", "modify", "dismiss", name="decision_action", native_enum=False),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("modified_sizing", sa.JSON(), nullable=True),
        sa.Column(
            "decided_by",
            sa.Enum("user", "auto", name="decided_by", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["suggestions.id"],
            name=op.f("fk_decisions_suggestion_id_suggestions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_table(
        "orders",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "asset_class",
            sa.Enum("equity", "crypto", name="asset_class", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "side", sa.Enum("buy", "sell", name="order_side", native_enum=False), nullable=False
        ),
        sa.Column(
            "order_type",
            sa.Enum("market", "limit", name="order_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("qty", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "validated",
                "rejected",
                "submitted",
                "filled",
                "cancelled",
                name="order_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("rejected_reason", sa.String(length=500), nullable=True),
        sa.Column("suggestion_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_orders_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["suggestions.id"],
            name=op.f("fk_orders_suggestion_id_suggestions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_orders_idempotency_key")),
    )
    op.create_table(
        "fills",
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("qty", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
    )
    op.create_table(
        "risk_events",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "breach",
                "veto",
                "auto_pause",
                "reconcile_discrepancy",
                name="risk_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=True),
        sa.Column("suggestion_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_risk_events_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_risk_events_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["suggestions.id"],
            name=op.f("fk_risk_events_suggestion_id_suggestions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_events")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_events")
    op.drop_table("fills")
    op.drop_table("orders")
    op.drop_table("decisions")
    op.drop_table("data_snapshots")
    op.drop_table("watchlist_items")
    op.drop_table("suggestions")
    op.drop_table("risk_limits")
    op.drop_table("positions")
    op.drop_table("journal_entries")
    op.drop_table("cash_balances")
    op.drop_table("agent_runs")
    op.drop_table("watchlists")
    op.drop_table("risk_profiles")
    op.drop_table("accounts")
    op.drop_table("users")
    # ### end Alembic commands ###
