"""S2.2 evidence docs

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-09 00:54:06.712077

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_docs",
        sa.Column("external_id", sa.String(length=512), nullable=False),
        sa.Column("doc_type", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_docs")),
        sa.UniqueConstraint("external_id", name=op.f("uq_evidence_docs_external_id")),
    )
    # Postgres: full-text search over title+body (S2.2 retrieval). evidence_docs is a shared
    # market-data corpus (no user_id) — deliberately outside RLS.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE evidence_docs ADD COLUMN search_tsv tsvector "
            "GENERATED ALWAYS AS (to_tsvector('english', title || ' ' || body)) STORED"
        )
        op.execute("CREATE INDEX ix_evidence_docs_tsv ON evidence_docs USING GIN (search_tsv)")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_evidence_docs_tsv")
    op.drop_table("evidence_docs")
